config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :recipes
  resources :foods
  resources :recipe_foods

  root "recipes#index"
  delete '/foods/:id', to: 'food#destroy', as: "delete_food"
  get '/public_recipes', to: 'recipes#public_recipes', as: "public_recipes"
  get '/shopping_list', to: 'recipes#shopping_list', as: "shopping_list"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:foods, :recipe_foods).find(params[:id])
    @foods_id_from_recipe = @recipe.foods.collect(&:id)
    @current_food_options = current_user.foods.collect do |f|
      ["#{f.name} / #{f.measurement_unit}", f.id] unless @recipe.foods.collect(&:id).include?(f.id)
    end.compact
    session[:current_recipe] = @recipe
    session[:current_food_options] = @current_food_options
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, :recipe_foods).where('public = true').order(created_at: :desc)
  end

  def shopping_list
    @recipe_hash = session[:current_recipe]
    if @recipe_hash.nil?
      @foods_id_from_recipe = []
    else
      # rubocop:disable Style/OpenStructUse
      @r_object = OpenStruct.new(@recipe_hash)
      @recipe = Recipe.includes(:foods, :recipe_foods).find(@r_object.id)
      @foods_id_from_recipe = @recipe.foods.collect(&:id)
      @total_price = 0
      @recipe.recipe_foods.where(recipe_id: @recipe.id).each do |rf|
        price = (rf.food.price * rf.quantity).round(2)
        @total_price += price
      end
      # rubocop:enable Style/OpenStructUse
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <h2>
    <%= recipe.name %>
  </h2>

  <% unless current_page?(:controller => 'recipes', :action => 'index') || current_page?(:controller => 'recipes', :action => 'new') %>
    <p>
      <strong>Preparation time:</strong>
      <% if recipe.preparation_time == 1 %>
        <%= recipe.preparation_time %> minute
      <% else %>
        <%= recipe.preparation_time %> minutes
      <% end %>
    </p>
  
    <p>
      <strong>Cooking time:</strong>
      <% if recipe.cooking_time == 1 %>
        <%= recipe.cooking_time %> minute
      <% else %>
        <%= recipe.cooking_time %> minutes
      <% end %>
    </p>
  <% end %>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <% unless current_page?(:controller => 'recipes', :action => 'index') %>
    <p>
      <strong>Public:</strong>
      <%= check_box("public", recipe.id, {checked: recipe.public, disabled: true}) %>
    </p>
  <% end %>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="title-container flex">
  <h1>Your Recipes</h1>
</div>

<div class="flex column">
  <% @recipes.each do |recipe| %>
    <div class="flex-row align-center">
      <div class="flex-title">
        <h3 class="recipe-name"><%= link_to recipe.name, recipe %></h2>
        <%= button_to "REMOVE", @recipe, method: :delete %>
      </div>
      <div class="flex-desc">
        <h4><%= recipe.description %></h4>
      </div>
    </div>
  <% end %>
</div>

<%= button_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="title-container flex">
  <h1>Public Recipes</h1>
</div>

<% unless @public_recipes.empty?%>
  <div class="flex column">
    <% @public_recipes.each do |recipe| %>
      <div class="flex-row align-center">
        <div class="flex-title">
          <h3 class="recipe-name"><%= link_to recipe.name, recipe %></h4><p>By <%= recipe.user.name %></h3>
        </div>
        <div class="flex-desc">
          <h5>Total food items: <%= (recipe.recipe_foods.collect { |rf| rf.quantity }).sum %></h5>
          <h5>Total price: $ <%= (recipe.recipe_foods.includes(:food).collect { |rf| rf.quantity * rf.food.price }).sum.round(2) %></h5>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No public recipes available</p>
<% end %>

app/views/recipes/shopping_list.html.erb
<% if @recipe.nil? %>
<h1>Shopping List</h1>
<% else %>
<h1>Shopping List for <%= @recipe.name %></h1>
<% end %>
<% unless @foods_id_from_recipe.empty? %>
<div class="title-container flex">
  <h4>Amount of foods items to buy: <%= @foods_id_from_recipe.length %></h4>
  <h4>Total value of food needed: <%= @total_price %></h4>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
      <% @recipe.recipe_foods.where(recipe_id: @recipe.id).each do |rf| %>
    <tr>
        <td><%= rf.food.name %></td>
        <td><%= rf.quantity %> <%= rf.food.measurement_unit %></td>
        <td>$ <%= (rf.food.price * rf.quantity).round(2) %></td>
    <tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>0 items to buy</h4>
<% end %>

app/views/recipes/show.html.erb
<%= render @recipe %>

<div class="flex space-between">
  <%= button_to "Generate Shopping List", shopping_list_path, method: :get%>
  <%= button_to "Create New Food", new_food_path, method: :get%>
</div>
<hr/>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.where(recipe_id: @recipe.id).each do |rf| %>
      <tr>
        <td><%= rf.food.name %></td>
        <td><%= rf.quantity %> <%= rf.food.measurement_unit %></td>
        <td>$ <%= (rf.food.price * rf.quantity).round(2) %></td>
        <% if can? :manage, rf.food %>
          <td class="flex btn-manage">
            <%= button_to "Modify", edit_recipe_food_path(rf), method: :get %>
            <%= button_to "Remove", rf, {
              :method => :delete,
              :onclick => "setTimeout(() => {
                this.parentNode.parentNode.parentNode.remove();
                document.getElementById('food-fb').innerText = 'There is food available to add';
                document.getElementById('btn-add-food').disabled = false;
                }, 100);"
            } %>
          </td>
        <% else %>
          <td> - </td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td>
        <% if @current_food_options.empty? %>
          <span id="food-fb">No food available to add</span>
        <% else %>
          <span id="food-fb">There is food available to add</span>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td>
        <% if @current_food_options.empty? %>
          <%= button_to "Add new ingredient", new_recipe_food_path, { :id => "btn-add-food", :method => :get, :disabled => true } %>
        <% else %>
          <%= button_to "Add new ingredient", new_recipe_food_path, { :id => "btn-add-food", :method => :get } %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>
  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>