config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :recipes
  resources :foods
  resources :recipe_foods

  root "recipes#index"
  delete '/foods/:id', to: 'food#destroy', as: "delete_food"
  get '/public_recipes', to: 'recipes#public_recipes', as: "public_recipes"
  get '/shopping_list', to: 'recipes#shopping_list', as: "shopping_list"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.includes(%i[recipe food]).all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = if session[:current_recipe].nil?
                     RecipeFood.new(recipe_food_params)
                   else
                     RecipeFood.new(recipe_food_params.merge(recipe_id: session[:current_recipe]['id']))
                   end
    respond_to do |format|
      if @recipe_food.save
        format.html do
          redirect_to recipe_path(id: @recipe_food.recipe_id), notice: 'Recipe food was successfully created.'
        end
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    if @recipe_food.destroy
      flash.now[:notice] = 'The food from your recipe was successfully destroyed.'
    else
      flash.now[:alert] = 'Error trying to delete this food'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :recipe_id, style: "display: block" %>
    <% if session[:current_recipe].nil? %>
      <%= form.select :recipe_id, options_for_select(current_user.recipes.collect { |r| [r.name, r.id] }) %>
    <% else %>
      <%= form.select :recipe_id, options_for_select(current_user.recipes.collect { |r| [r.name, r.id] }, session[:current_recipe]['id']), {}, :disabled => true %>
    <% end %>
  </div>

  <div>
    <%= form.label :food_id, style: "display: block" %>
    <% if session[:current_food_options].nil? %>
      <%= form.select :food_id, options_for_select(current_user.foods.collect { |f| ["#{f.name} / #{f.measurement_unit}", f.id] }.compact) %>
    <% else %>
      <%= form.select :food_id, options_for_select(session[:current_food_options]) %>
    <% end %>
  </div>

  <div>
  <% if session[:current_recipe].nil? %>
    <%= form.submit %>
  <% else %>
    <%= form.submit "Add food to the recipe" %>
  <% end %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe.name %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food.name %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<% if session[:current_recipe].nil? %>
  <h1>New recipe food</h1>
<% else %>
  <h1>Add new food to the <%= session[:current_recipe]['name'] %> recipe</h1>
<% end %>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <% if session[:current_recipe].nil? %>
    <%= link_to "Back to recipe foods", recipe_foods_path %>
  <% else %>
    <%= link_to "Back to recipe", recipe_path(session[:current_recipe]['id']) %>
  <% end %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>